### ISSUE TITLE
RuntimeError while creating Portfolio('10-K')

### ISSUE THREAD

**Issue by Lanikeha** [john-friedman/datamule-python#30]
At the end I put details of my software versions.
I have downloded AAPL submissions via
```
from datamule import Downloader
downloader = Downloader()
downloader.download_submissions('10-K', ticker='AAPL')
```
I left only one submission to make it more simple. Then followed example from documentation:
```
from datamule import Portfolio
portfolio = Portfolio('10-K')
```
That caused an error below:
```
PS C:\Users\krzys\SEC> & C:/Users/krzys/SEC/.venv/Scripts/python.exe c:/Users/krzys/SEC/portfolio.py
Loading 1 submissions
Loading submissions:   0%|                                                                                                                                                                  | 0/1 [00:00<?, ?it/s]Loading 1 submissions
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\krzys\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\multiprocessing\spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krzys\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\multiprocessing\spawn.py", line 131, in _main
    prepare(preparation_data)
  File "C:\Users\krzys\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\multiprocessing\spawn.py", line 246, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\krzys\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\multiprocessing\spawn.py", line 297, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 291, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Users\krzys\SEC\portfolio.py", line 4, in <module>
    portfolio = Portfolio('10-K')
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\krzys\SEC\.venv\Lib\site-packages\datamule\portfolio.py", line 15, in __init__
    executor.map(Submission, folders),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krzys\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\concurrent\futures\process.py", line 837, in map
    results = super().map(partial(_process_chunk, fn),
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krzys\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\concurrent\futures\_base.py", line 608, in map
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krzys\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\concurrent\futures\_base.py", line 608, in <listcomp>
    fs = [self.submit(fn, *args) for args in zip(*iterables)]
          ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krzys\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\concurrent\futures\process.py", line 808, in submit
    self._adjust_process_count()
  File "C:\Users\krzys\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\concurrent\futures\process.py", line 767, in _adjust_process_count
    self._spawn_process()
  File "C:\Users\krzys\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\concurrent\futures\process.py", line 785, in _spawn_process
    p.start()
  File "C:\Users\krzys\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\krzys\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\multiprocessing\context.py", line 336, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\krzys\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krzys\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\multiprocessing\spawn.py", line 164, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\krzys\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\multiprocessing\spawn.py", line 140, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

        To fix this issue, refer to the "Safe importing of main module"
        section in https://docs.python.org/3/library/multiprocessing.html

Loading submissions:   0%|                                                                                                                                                                  | 0/1 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "c:\Users\krzys\SEC\portfolio.py", line 4, in <module>
    portfolio = Portfolio('10-K')
                ^^^^^^^^^^^^^^^^^
  File "C:\Users\krzys\SEC\.venv\Lib\site-packages\datamule\portfolio.py", line 14, in __init__
    self.submissions = list(tqdm(
                       ^^^^^^^^^^
  File "C:\Users\krzys\SEC\.venv\Lib\site-packages\tqdm\std.py", line 1181, in __iter__
    for obj in iterable:
  File "C:\Users\krzys\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\concurrent\futures\process.py", line 620, in _chain_from_iterable_of_lists
    for element in iterable:
  File "C:\Users\krzys\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\concurrent\futures\_base.py", line 619, in result_iterator
    yield _result_or_cancel(fs.pop())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krzys\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\concurrent\futures\_base.py", line 317, in _result_or_cancel
    return fut.result(timeout)
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krzys\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\krzys\AppData\Roaming\uv\python\cpython-3.11.11-windows-x86_64-none\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
PS C:\Users\krzys\SEC> 
```
I have used uv to create project with python 3.11 and dependencies as below:
```
PS C:\Users\krzys\SEC> uv tree
Resolved 32 packages in 0.89ms
sec v0.1.0
├── datamule v0.421
│   ├── aiofiles v24.1.0
│   ├── aiohttp v3.11.11
│   │   ├── aiohappyeyeballs v2.4.4
│   │   ├── aiosignal v1.3.2
│   │   │   └── frozenlist v1.5.0
│   │   ├── attrs v24.3.0
│   │   ├── frozenlist v1.5.0
│   │   ├── multidict v6.1.0
│   │   ├── propcache v0.2.1
│   │   └── yarl v1.18.3
│   │       ├── idna v3.10
│   │       ├── multidict v6.1.0
│   │       └── propcache v0.2.1
│   ├── aiolimiter v1.2.1
│   ├── nest-asyncio v1.6.0
│   ├── polars v1.18.0
│   ├── pytz v2024.2
│   ├── requests v2.32.3
│   │   ├── certifi v2024.12.14
│   │   ├── charset-normalizer v3.4.1
│   │   ├── idna v3.10
│   │   └── urllib3 v2.3.0
│   ├── selectolax v0.3.27
│   ├── setuptools v75.6.0
│   ├── tqdm v4.67.1
│   │   └── colorama v0.4.6
│   └── zstandard v0.23.0
└── pandas v2.2.3
    ├── numpy v2.2.1
    ├── python-dateutil v2.9.0.post0
    │   └── six v1.17.0
    ├── pytz v2024.2
    └── tzdata v2024.2
```
Thanks for help!

**Comment by john-friedman** [comment]
Ah, I think I see the error. Will push a fix later today.

Can you use a jupyter notebook .ipynb file? .ipynb works on my end - .py does not.

**Comment by Lanikeha** [comment]
Jupyter works. Thank you very much for your help.
Nevertheless I have no idea how to use it in practice.
I think I have to wait for more begineer-friendly documentation or examples.

Keep up the godd work!

**Comment by john-friedman** [comment]
Just pushed the fix to Portfolio should work normally now.

What are you trying to do? I am updating the docs this week to make it more beginner friendly.

**Comment by Lanikeha** [comment]
> What are you trying to do? I am updating the docs this week to make it more beginner friendly.

First thing would be to get Quarterly Income Statements for a selected company into a DataFrame.

**Comment by john-friedman** [comment]
Hmm, you may want to check out https://github.com/dgunning/edgartools. Quarterly income is in XBRL, and his package is a bit more user friendly for that.

I will be adding good XBRL support soon, but I haven't figured out how I want to do it yet.

**Comment by Lanikeha** [comment]
Thanks a lot! It looks great for my needs.

**Comment by john-friedman** [comment]
Glad I could help!
